title: Muskoin 
email: muskoin@protonmail.com
avatar: "/media/svg/logo_black.svg"

social:
  email: "muskoin@protonmail.com"
  github: muskoin 
  twitter: muskoinapp 

remote_theme: jekyll/minima
minima: 
  skin: dark
  date_format: "%b %-d, %Y"
